version: '3.8'
services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sgt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/sgt_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps/

volumes:
  postgres_data:
